/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class co_pokeum_linesdk_unreal_UnrealBridge */

#ifndef _Included_co_pokeum_linesdk_unreal_UnrealBridge
#define _Included_co_pokeum_linesdk_unreal_UnrealBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     co_pokeum_linesdk_unreal_UnrealBridge
 * Method:    sendMessage
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_co_pokeum_linesdk_unreal_UnrealBridge_sendMessage
(JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
